package com.stal111.forbidden_arcanus.item;

import com.stal111.forbidden_arcanus.Main;
import com.stal111.forbidden_arcanus.block.ModBlocks;
import com.stal111.forbidden_arcanus.item.armor.BasicArmor;
import com.stal111.forbidden_arcanus.item.armor.ModArmorMaterial;
import com.stal111.forbidden_arcanus.item.tool.ToolAxe;
import com.stal111.forbidden_arcanus.item.tool.ToolDracoArcanusScepter;
import com.stal111.forbidden_arcanus.item.tool.ToolHoe;
import com.stal111.forbidden_arcanus.item.tool.ToolMulti;
import com.stal111.forbidden_arcanus.item.tool.ToolPickaxe;
import com.stal111.forbidden_arcanus.item.tool.ToolShovel;
import com.stal111.forbidden_arcanus.item.tool.ToolSword;

import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.minecraft.item.ItemTier;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.registries.ObjectHolder;

@ObjectHolder(Main.MODID)
public class ModItems {

	public static final Item
			arcane_gold_ingot = null,
			arcane_gold_nugget = null,
			orb_of_temporary_flight = null,
			chorus_pearl = null,
			spectral_eye_amulet = null,
			soul = null,
			dark_soul = null,
			pixi = null,
			corrupt_pixi = null,
			arcane_crystal = null,
			arcane_crystal_dust = null,
			mundabitur_dust = null,
			corrupti_dust = null,
			dark_matter = null,
			ender_pearl_fragment = null,
			rune = null,
			dark_rune = null,
			rune_bag = null,
			dark_rune_bag = null,
			skull = null,
			obsidian_skull = null,
			obsidian_skull_shield = null,
			obsidian_with_iron = null,
			obsidian_ingot = null,
			dark_nether_star = null,
			dragon_scale = null,
			silver_dragon_scale = null,
			golden_dragon_scale = null,
			aquatic_dragon_scale = null,
			rotten_leather = null,
			leather_of_the_sea = null,
			golden_feather = null,
			golden_orchid_seeds = null,
			seed_bulet = null,
			aku_aku = null,
			golden_aku_aku = null,
			edelwood_stick = null,
			infernum_pickaxe = null,
			slimec_pickaxe = null,
			runic_battleaxe = null,
			sacred_scepter = null,
			draco_arcanus_staff = null,
			draco_arcanus_sword = null,
			draco_arcanus_shovel = null,
			draco_arcanus_pickaxe = null,
			draco_arcanus_axe = null,
			draco_arcanus_hoe = null,
			draco_arcanus_scepter = null,
			arcane_golden_sword = null,
			arcane_golden_shovel = null,
			arcane_golden_pickaxe = null,
			arcane_golden_axe = null,
			arcane_golden_hoe = null,
			reinforced_arcane_golden_sword = null,
			reinforced_arcane_golden_shovel = null,
			reinforced_arcane_golden_pickaxe = null,
			reinforced_arcane_golden_axe = null,
			reinforced_arcane_golden_hoe = null,
			obsidian_sword = null,
			obsidian_shovel = null,
			obsidian_pickaxe = null,
			obsidian_axe = null,
			obsidian_hoe = null,
			battle_skull = null,
			bone_sword = null,
			bone_shovel = null,
			bone_pickaxe = null,
			bone_axe = null,
			bone_hoe = null,
			draco_arcanus_helmet = null,
			draco_arcanus_chestplate = null,
			draco_arcanus_leggings = null,
			draco_arcanus_boots = null,
			tyr_helmet = null,
			tyr_chestplate = null,
			tyr_leggings = null,
			tyr_boots = null,
			mortem_helmet = null,
			mortem_chestplate = null,
			mortem_leggings = null,
			mortem_boots = null,
			arcane_gold_helmet = null,
			arcane_gold_chestplate = null,
			arcane_gold_leggings = null,
			arcane_gold_boots = null,
			obsidian_helmet = null,
			obsidian_shoulder_pads = null,
			obsidian_knee_pads = null,
			obsidian_boots = null;

	public static void register(RegistryEvent.Register<Item> registry) {
		registerAll(registry,
				new BasicItem("arcane_gold_ingot"),
				new BasicItem("arcane_gold_nugget"),
				new ItemOrbOfTemporaryFlight("orb_of_temporary_flight"),
				new ChorusPearlItem("chorus_pearl"),
				new SpectralEyeAmuletItem("spectral_eye_amulet"),
				new BasicItem("soul"),
				new BasicItem("dark_soul"),
				new PixiItem("pixi", 265),
				new PixiItem("corrupt_pixi", 0),
				new BasicItem("arcane_crystal"),
				new BasicItem("arcane_crystal_dust"),
				new BasicItem("mundabitur_dust"),
				new BasicItem("corrupti_dust"),
				new BasicItem("dark_matter"),
				new BasicItem("ender_pearl_fragment"),
				new BasicItem("rune"),
				new BasicItem("dark_rune"),
				new BasicItem("rune_bag"),
				new BasicItem("dark_rune_bag"),
				new BasicItem("skull"),
				new ObsidianSkullItem("obsidian_skull"),
				new ObsidianSkullShieldItem("obsidian_skull_shield"),
				new BasicItem("obsidian_with_iron"),
				new BasicItem("obsidian_ingot"),
				new EnchantmentGlintItem("dark_nether_star"),
				new BasicItem("dragon_scale"),
				new BasicItem("silver_dragon_scale"),
				new BasicItem("golden_dragon_scale"),
				new BasicItem("aquatic_dragon_scale"),
				new BasicItem("rotten_leather"),
				new BasicItem("leather_of_the_sea"),
				new BasicItem("golden_feather"),
				new BasicItem("golden_orchid_seeds"),
				new BasicItem("seed_bulet"),
				new BasicItem("aku_aku"),
				new BasicItem("golden_aku_aku"),
				new BasicItem("edelwood_stick"),
				new ToolPickaxe("infernum_pickaxe", ItemTier.DIAMOND, 1, -2.8F),
				new ToolPickaxe("slimec_pickaxe", ItemTier.DIAMOND, 1, -2.5F),
				new ToolAxe("runic_battleaxe", ItemTier.DIAMOND, 1, -2.8F),
				new BasicItem("sacred_scepter"),
				new BasicItem("draco_arcanus_staff"),
				new ToolSword("draco_arcanus_sword", ModItemTier.DRACO_ARCANUS, 4, -2.2F),
				new ToolShovel("draco_arcanus_shovel", ModItemTier.DRACO_ARCANUS, 2.5F, -2.8F),
				new ToolPickaxe("draco_arcanus_pickaxe", ModItemTier.DRACO_ARCANUS, 2, -2.6F),
				new ToolAxe("draco_arcanus_axe", ModItemTier.DRACO_ARCANUS, 6.0F, -2.8F),
				new ToolHoe("draco_arcanus_hoe", ModItemTier.DRACO_ARCANUS, 0.0F),
				new ToolDracoArcanusScepter("draco_arcanus_scepter"),
				new ToolSword("arcane_golden_sword", ModItemTier.ARCANE_GOLDEN, 3, -2.4F),
				new ToolShovel("arcane_golden_shovel", ModItemTier.ARCANE_GOLDEN, 1.5F, -3.0F),
				new ToolPickaxe("arcane_golden_pickaxe", ModItemTier.ARCANE_GOLDEN, 1, -2.8F),
				new ToolAxe("arcane_golden_axe", ModItemTier.ARCANE_GOLDEN, 5, -3.0F),
				new ToolHoe("arcane_golden_hoe", ModItemTier.ARCANE_GOLDEN, 0.0F),
				new ToolSword("reinforced_arcane_golden_sword", ModItemTier.REINFORCED_ARCANE_GOLDEN, 3, -2.4F),
				new ToolShovel("reinforced_arcane_golden_shovel", ModItemTier.REINFORCED_ARCANE_GOLDEN, 1.5F, -3.0F),
				new ToolPickaxe("reinforced_arcane_golden_pickaxe", ModItemTier.REINFORCED_ARCANE_GOLDEN, 1, -2.8F),
				new ToolAxe("reinforced_arcane_golden_axe", ModItemTier.REINFORCED_ARCANE_GOLDEN, 5, -3.0F),
				new ToolHoe("reinforced_arcane_golden_hoe", ModItemTier.REINFORCED_ARCANE_GOLDEN, 0.0F),
				new ToolSword("obsidian_sword", ModItemTier.OBSIDIAN, 3, -2.4F),
				new ToolShovel("obsidian_shovel", ModItemTier.OBSIDIAN, 1.5F, -3.0F),
				new ToolPickaxe("obsidian_pickaxe", ModItemTier.OBSIDIAN, 1, -2.8F),
				new ToolAxe("obsidian_axe", ModItemTier.OBSIDIAN, 5, -3.0F),
				new ToolHoe("obsidian_hoe", ModItemTier.OBSIDIAN, 0.0F),
				new ToolMulti("battle_skull", 3, -2.4F, ModItemTier.BONE),
				new ToolSword("bone_sword", ModItemTier.BONE, 3, -2.4F),
				new ToolShovel("bone_shovel", ModItemTier.BONE, 1.5F, -3.0F),
				new ToolPickaxe("bone_pickaxe", ModItemTier.BONE, 1, -2.8F),
				new ToolAxe("bone_axe", ModItemTier.BONE, 5, -3.0F),
				new ToolHoe("bone_hoe", ModItemTier.BONE, 0.0F),
				new BasicArmor("draco_arcanus_helmet", ModArmorMaterial.DRACO_ARCANUS, EntityEquipmentSlot.HEAD),
				new BasicArmor("draco_arcanus_chestplate", ModArmorMaterial.DRACO_ARCANUS, EntityEquipmentSlot.CHEST),
				new BasicArmor("draco_arcanus_leggings", ModArmorMaterial.DRACO_ARCANUS, EntityEquipmentSlot.LEGS),
				new BasicArmor("draco_arcanus_boots", ModArmorMaterial.DRACO_ARCANUS, EntityEquipmentSlot.FEET),
				new BasicArmor("tyr_helmet", ModArmorMaterial.TYR, EntityEquipmentSlot.HEAD),
				new BasicArmor("tyr_chestplate", ModArmorMaterial.TYR, EntityEquipmentSlot.CHEST),
				new BasicArmor("tyr_leggings", ModArmorMaterial.TYR, EntityEquipmentSlot.LEGS),
				new BasicArmor("tyr_boots", ModArmorMaterial.TYR, EntityEquipmentSlot.FEET),
				new BasicArmor("mortem_helmet", ModArmorMaterial.MORTEM, EntityEquipmentSlot.HEAD),
				new BasicArmor("mortem_chestplate", ModArmorMaterial.MORTEM, EntityEquipmentSlot.CHEST),
				new BasicArmor("mortem_leggings", ModArmorMaterial.MORTEM, EntityEquipmentSlot.LEGS),
				new BasicArmor("mortem_boots", ModArmorMaterial.MORTEM, EntityEquipmentSlot.FEET),
				new BasicArmor("arcane_gold_helmet", ModArmorMaterial.ARCANE_GOLD, EntityEquipmentSlot.HEAD),
				new BasicArmor("arcane_gold_chestplate", ModArmorMaterial.ARCANE_GOLD, EntityEquipmentSlot.CHEST),
				new BasicArmor("arcane_gold_leggings", ModArmorMaterial.ARCANE_GOLD, EntityEquipmentSlot.LEGS),
				new BasicArmor("arcane_gold_boots", ModArmorMaterial.ARCANE_GOLD, EntityEquipmentSlot.FEET),
				new BasicArmor("obsidian_helmet", ModArmorMaterial.OBSIDIAN, EntityEquipmentSlot.HEAD),
				new BasicArmor("obsidian_shoulder_pads", ModArmorMaterial.OBSIDIAN, EntityEquipmentSlot.CHEST),
				new BasicArmor("obsidian_knee_pads", ModArmorMaterial.OBSIDIAN, EntityEquipmentSlot.LEGS),
				new BasicArmor("obsidian_boots", ModArmorMaterial.OBSIDIAN, EntityEquipmentSlot.FEET));

		ModBlocks.registerItemBlocks(registry);
	}

	public static void registerAll(RegistryEvent.Register<Item> registry, Item... items) {
		for (Item item : items) {
			registry.getRegistry().register(item);
		}
	}

}
